### ISSUE TITLE
Can't run the compiled example

### ISSUE THREAD

**Issue by sarna** [mmhelloworld/idris-jvm#74]
Running compiled pythag.idr fails with the following error message:
`Exception in thread "main" java.lang.NoClassDefFoundError: io/github/mmhelloworld/idrisjvm/runtime/Runtime
	at main.Main.main(Main.idr)
Caused by: java.lang.ClassNotFoundException: io.github.mmhelloworld.idrisjvm.runtime.Runtime
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more`
Running without compilation (with idris-jvm-runtime.jar) works fine though.
Decompiled .class file: https://pastebin.com/nbiZ0NFA
OS: Arch Linux 64-bit
`java -version`
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
`idris --version`
1.2.0

**Comment by mmhelloworld** [comment]
Thank you for trying out idris-jvm. How are you running the class? You need to have idris-jvm-runtime.jar in the classpath for the JVM when you run it.

**Comment by sarna** [comment]
Well, I goofed up. When I run it like this `java -cp target:/path/to/idris-jvm-runtime-1.0-SNAPSHOT.jar main.Main` it works :)
Thanks for creating idris-jvm, it looks really neat!
